/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.nhatro.ui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.nhatro.dao.ChiNhanhDAO;
import poly.nhatro.dao.DienNuocDao;
import poly.nhatro.dao.impl.ChiNhanhDAOImpl;
import poly.nhatro.dao.impl.DienNuocDaoImpl;
import poly.nhatro.entity.DienNuoc;

/**
 *
 * @author Phu Pham
 */
public class DienNuocPanel extends javax.swing.JPanel {

    /**
     * Creates new form DienNuocPanel
     */
    public DienNuocPanel() {
        initComponents();
        initComboBoxChiNhanh();
        initEventHandlers();
        loadDuLieuToanBo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxLocChiNhanh = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();
        txtThangNam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtThang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDien = new javax.swing.JTextField();
        txtNuoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLy = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý chỉ số điện nước");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lọc theo chi nhánh:");

        cbxLocChiNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLocChiNhanhActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setInheritsPopupMenu(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tháng năm muốn xuất hóa đơn");

        btnXuatHoaDon.setBackground(new java.awt.Color(51, 153, 255));
        btnXuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXuatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatHoaDon.setText("Xuất hóa đơn hàng loạt");
        btnXuatHoaDon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        txtThangNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThangNamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã Số:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã Phòng:");

        txtThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Năm:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số Điện:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Số Nước:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tháng:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(775, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        tblQuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Số", "Mã Phòng", "Tháng", "Năm", "Số Điện", "Số Nước"
            }
        ));
        tblQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLy);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Làm mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear)
                        .addComponent(btnDelete)
                        .addComponent(btnSua)
                        .addComponent(btnAdd))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxLocChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbxLocChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLocChiNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLocChiNhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLocChiNhanhActionPerformed

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThangActionPerformed

    private void txtThangNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThangNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThangNamActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyMouseClicked
        // TODO add your handling code here:
        txtID.setEnabled(false);
        txtMaPhong.setEnabled(false);
    }//GEN-LAST:event_tblQuanLyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JComboBox<String> cbxLocChiNhanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQuanLy;
    private javax.swing.JTextField txtDien;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNuoc;
    private javax.swing.JTextField txtThang;
    private javax.swing.JTextField txtThangNam;
    // End of variables declaration//GEN-END:variables

    private DienNuocDao soDienNuocDAO = new DienNuocDaoImpl();
    ChiNhanhDAO chiNhanhDAO = new ChiNhanhDAOImpl();

    public void initEventHandlers() {
        btnAdd.addActionListener(e -> themSoDienNuoc());
        btnSua.addActionListener(e -> suaSoDienNuoc());
        btnDelete.addActionListener(e -> xoaSoDienNuoc());
        btnClear.addActionListener(e -> lamMoiForm());
        cbxLocChiNhanh.addActionListener(e -> locTheoChiNhanh());
        btnXuatHoaDon.addActionListener(e -> xuatHoaDon());
        tblQuanLy.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = tblQuanLy.getSelectedRow();
                if (row != -1) {
                    txtID.setText(tblQuanLy.getValueAt(row, 0).toString());
                    txtMaPhong.setText(tblQuanLy.getValueAt(row, 1).toString());
                    txtThang.setText(tblQuanLy.getValueAt(row, 2).toString());
                    txtNam.setText(tblQuanLy.getValueAt(row, 3).toString());
                    txtDien.setText(tblQuanLy.getValueAt(row, 4).toString());
                    txtNuoc.setText(tblQuanLy.getValueAt(row, 5).toString());
                }
            }
        });
        // Load dữ liệu ban đầu
        loadDuLieuToanBo();
    }

    private void themSoDienNuoc() {
        try {
            // Lấy tên chi nhánh từ ComboBox
            String tenChiNhanh = (String) cbxLocChiNhanh.getSelectedItem();

            // Lấy ID chi nhánh từ DAO
            int idChiNhanh = chiNhanhDAO.layIDTheoTen(tenChiNhanh);

            if (idChiNhanh == -1) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy ID chi nhánh!");
                return;
            }

            

            DienNuoc sdn = new DienNuoc();
            sdn.setIdChiNhanh(idChiNhanh);
            sdn.setIdPhong(Integer.parseInt(txtMaPhong.getText()));
            sdn.setThang(Integer.parseInt(txtThang.getText()));
            sdn.setNam(Integer.parseInt(txtNam.getText()));
            sdn.setSoDien(Integer.parseInt(txtDien.getText()));
            sdn.setSoNuoc(Integer.parseInt(txtNuoc.getText()));
            
            if (soDienNuocDAO.kiemTraTrungThangNam(sdn.getIdPhong(), sdn.getThang(), sdn.getNam())) {
                JOptionPane.showMessageDialog(this, "Phòng đã có dữ liệu điện nước cho tháng "
                        + sdn.getThang() + "/" + sdn.getNam());
                return;
            }

            soDienNuocDAO.insert(sdn);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadDuLieuToanBo();
            lamMoiForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thêm: " + e.getMessage());
            e.printStackTrace();
        }
        if (!validateForm()) {
            return;
        }

    }

    private void suaSoDienNuoc() {
        try {
            DienNuoc sdn = new DienNuoc();
            sdn.setMaSo(Integer.parseInt(txtID.getText()));
            sdn.setIdPhong(Integer.parseInt(txtMaPhong.getText()));
            sdn.setThang(Integer.parseInt(txtThang.getText()));
            sdn.setNam(Integer.parseInt(txtNam.getText()));
            sdn.setSoDien(Integer.parseInt(txtDien.getText()));
            sdn.setSoNuoc(Integer.parseInt(txtNuoc.getText()));
            soDienNuocDAO.update(sdn);
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            loadDuLieuToanBo();
            lamMoiForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi sửa: " + e.getMessage());
        }
        if (!validateForm()) {
            return;
        }

    }

    private void xoaSoDienNuoc() {
        try {
            int maso = Integer.parseInt(txtID.getText());
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                soDienNuocDAO.deleteById(maso);
                JOptionPane.showMessageDialog(this, "Xoá thành công!");
                loadDuLieuToanBo();
                lamMoiForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xoá: " + e.getMessage());
        }
    }

    private void lamMoiForm() {
        txtID.setText("");
        txtMaPhong.setText("");
        txtThang.setText("");
        txtNam.setText("");
        txtDien.setText("");
        txtNuoc.setText("");
        tblQuanLy.clearSelection();

        txtID.setEnabled(true);
        txtMaPhong.setEnabled(true);
    }

    private void xuatHoaDon() {
        try {
            String tenChiNhanh = cbxLocChiNhanh.getSelectedItem().toString();
            int idChiNhanh = chiNhanhDAO.layIDTheoTen(tenChiNhanh);

            String thangNam = txtThangNam.getText(); // Ví dụ: "7/2025"
            String[] parts = thangNam.split("/");
            int thang = Integer.parseInt(parts[0]);
            int nam = Integer.parseInt(parts[1]);

            int tongTien = 0;

            List<DienNuoc> list = soDienNuocDAO.findByChiNhanhVaThangNam(idChiNhanh, thang, nam);
            DefaultTableModel model = (DefaultTableModel) tblQuanLy.getModel();
            model.setRowCount(0);

            for (DienNuoc sdn : list) {
                Object[] row = {
                    sdn.getMaSo(), sdn.getIdPhong(), sdn.getThang(), sdn.getNam(),
                    sdn.getSoDien(), sdn.getSoNuoc()
                };
                model.addRow(row);
                tongTien += sdn.getSoDien() * 3000 + sdn.getSoNuoc() * 10000; // ví dụ đơn giá
            }

            JOptionPane.showMessageDialog(this, "Tổng tiền tháng " + thang + "/" + nam + ": " + tongTien + " VNĐ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xuất hóa đơn: " + e.getMessage());
        }
    }

    private boolean validateForm() {
        if (txtMaPhong.getText().isEmpty() || txtThang.getText().isEmpty()
                || txtNam.getText().isEmpty() || txtDien.getText().isEmpty()
                || txtNuoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return false;
        }

        try {
            Integer.parseInt(txtMaPhong.getText());
            Integer.parseInt(txtThang.getText());
            Integer.parseInt(txtNam.getText());
            Integer.parseInt(txtDien.getText());
            Integer.parseInt(txtNuoc.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số!");
            return false;
        }

        return true;
    }

    private void initComboBoxChiNhanh() {
        try {
            List<String> branches = chiNhanhDAO.getAllBranchNames();
            cbxLocChiNhanh.removeAllItems();
            for (String name : branches) {
                cbxLocChiNhanh.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load chi nhánh: " + e.getMessage());
        }
    }

    private void locTheoChiNhanh() {
        try {
            String tenChiNhanh = (String) cbxLocChiNhanh.getSelectedItem();
            int idChiNhanh = chiNhanhDAO.layIDTheoTen(tenChiNhanh);
            List<DienNuoc> list = soDienNuocDAO.timTheoChiNhanh(idChiNhanh); // Đã thêm mới
            DefaultTableModel model = (DefaultTableModel) tblQuanLy.getModel();
            model.setRowCount(0);
            for (DienNuoc sdn : list) {
                Object[] row = {
                    sdn.getMaSo(), sdn.getIdPhong(), sdn.getThang(), sdn.getNam(),
                    sdn.getSoDien(), sdn.getSoNuoc()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lọc chi nhánh: " + e.getMessage());
        }
    }

    private void loadDuLieuToanBo() {
        List<DienNuoc> list = soDienNuocDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) tblQuanLy.getModel();
        model.setRowCount(0);
        for (DienNuoc sdn : list) {
            Object[] row = {
                sdn.getMaSo(), sdn.getIdPhong(), sdn.getThang(), sdn.getNam(),
                sdn.getSoDien(), sdn.getSoNuoc()
            };
            model.addRow(row);
        }
    }

}
