/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.nhatro.ui;

import poly.nhatro.entity.DienNuoc;
import poly.nhatro.dao.impl.DienNuocDAOImpl;
import poly.nhatro.dao.DienNuocDAO;
import poly.nhatro.dao.ChiNhanhDAO;
import poly.nhatro.dao.impl.ChiNhanhDAOImpl;
import poly.nhatro.entity.ChiNhanh;
import poly.nhatro.dao.impl.PhongDaoImpl; // Đảm bảo import đúng PhongDaoImpl
import poly.nhatro.entity.Phong;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.MouseEvent;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileOutputStream;
import java.io.File;
import java.io.IOException;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat; // Thêm import cho SimpleDateFormat
import java.util.Date; // Thêm import cho Date
import com.toedter.calendar.JDateChooser; // Thêm import cho JDateChooser
import javax.swing.JButton; // Thêm import cho JButton
import javax.swing.JDialog; // Thêm import cho JDialog
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.ImageIcon; // Thêm import cho ImageIcon

public class DienNuocPanel extends javax.swing.JPanel implements dienNuocController {

    private DienNuocDAO dienNuocDao;
    private ChiNhanhDAO chiNhanhDao;
    private PhongDaoImpl phongDao; // Đảm bảo sử dụng PhongDaoImpl
    private Map<String, Integer> chiNhanhMap;
    private Map<String, Integer> phongMap; // Thêm map để lưu trữ mã phòng và ID phòng
    private int currentIndex = -1;
    private List<DienNuoc> currentList;
// Định dạng ngày tháng theo yêu cầu: "Aug 1, 2025"
    private SimpleDateFormat dateFormat = new SimpleDateFormat("MMM d, yyyy");

    public DienNuocPanel() {
        initComponents();
        this.dienNuocDao = new DienNuocDAOImpl();
        this.chiNhanhDao = new ChiNhanhDAOImpl();
        this.phongDao = new PhongDaoImpl(); // Khởi tạo PhongDaoImpl
        this.chiNhanhMap = new HashMap<>();
        this.phongMap = new HashMap<>(); // Khởi tạo phongMap
        init();
        txtSoDienCu.setEditable(false); // Vô hiệu hóa nhập liệu
        txtSoNuocCu.setEditable(false); // Vô hiệu hóa nhập liệu
    }

    @Override
    public void init() {
        loadChiNhanhToComboBox();
        txtDienNuoc.setEditable(false); // ID Điện nước không cho sửa
        txtThangNam.setText(dateFormat.format(new Date())); // Đặt ngày hiện tại làm mặc định cho JTextField
        filterAndFillTable(); // Gọi phương thức này để lọc và điền dữ liệu ban đầu
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblHopDong5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienCu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSoNuocCu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboChiNhanh = new javax.swing.JComboBox<>();
        btnLocTheoChiNhanh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDienNuoc = new javax.swing.JTextField();
        txtSoDienMoi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoNuocMoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtThangNam = new javax.swing.JTextField();
        cboMaPhong = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDienNuoc = new javax.swing.JTable();
        btnExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblHopDong5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblHopDong5.setText("Điện nước");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(lblHopDong5)
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHopDong5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã phòng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Số nước cũ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Số điện cũ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Chi nhánh");

        cboChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChiNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChiNhanhActionPerformed(evt);
            }
        });

        btnLocTheoChiNhanh.setText("Lọc theo chi nhánh");
        btnLocTheoChiNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocTheoChiNhanhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Mã Điện Nước");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Số điện mới");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Số nước mới");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tháng năm");

        txtThangNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThangNamMouseClicked(evt);
            }
        });
        txtThangNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThangNamActionPerformed(evt);
            }
        });

        cboMaPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboChiNhanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoNuocCu)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cboMaPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDienNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                        .addComponent(btnLocTheoChiNhanh)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocTheoChiNhanh)
                    .addComponent(jLabel8)
                    .addComponent(txtDienNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cboMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoNuocCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tblDienNuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Chi nhánh", "Mã điện nước", "mã phòng", "Giá điện cũ", "Giá điện mới", "Giá nước cũ", "Giá nước mới", "Tháng năm"
            }
        ));
        tblDienNuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDienNuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDienNuoc);

        btnExcel.setText("Xuất Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi)
                    .addComponent(btnExcel))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLocTheoChiNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocTheoChiNhanhActionPerformed
        filterAndFillTable();
    }//GEN-LAST:event_btnLocTheoChiNhanhActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        this.Excel();
    }//GEN-LAST:event_btnExcelActionPerformed

    private void tblDienNuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDienNuocMouseClicked
        if (evt.getClickCount() == 1) { // Chỉ xử lý khi là một click đơn
            edit(); // Gọi phương thức edit() để hiển thị dữ liệu lên form
        }
        txtSoDienCu.setEditable(false);
    txtSoNuocCu.setEditable(false);
    }//GEN-LAST:event_tblDienNuocMouseClicked

    private void cboChiNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChiNhanhActionPerformed
        loadPhongToComboBox();
        filterAndFillTable();
    }//GEN-LAST:event_cboChiNhanhActionPerformed

    private void txtThangNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThangNamActionPerformed

    }//GEN-LAST:event_txtThangNamActionPerformed

    private void txtThangNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThangNamMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("MMM d, yyyy"); // Định dạng hiển thị trong JDateChooser

        // Cố gắng phân tích ngày hiện có trong txtThangNam để đặt cho JDateChooser
        try {
            Date currentDate = dateFormat.parse(txtThangNam.getText());
            dateChooser.setDate(currentDate);
        } catch (java.text.ParseException ex) {
            // Nếu không thể phân tích, đặt ngày hiện tại
            dateChooser.setDate(new Date());
        }

        JDialog dialog = new JDialog((Frame) null, "Chọn ngày", true); // Tạo JDialog với modal là true
        dialog.getContentPane().add(dateChooser, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Sau khi dialog đóng, lấy ngày đã chọn và cập nhật txtThangNam
        if (dateChooser.getDate() != null) {
            txtThangNam.setText(dateFormat.format(dateChooser.getDate()));
        }
    }//GEN-LAST:event_txtThangNamMouseClicked

    private void cboMaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaPhongActionPerformed

    }//GEN-LAST:event_cboMaPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLocTheoChiNhanh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChiNhanh;
    private javax.swing.JComboBox<String> cboMaPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHopDong5;
    private javax.swing.JTable tblDienNuoc;
    private javax.swing.JTextField txtDienNuoc;
    private javax.swing.JTextField txtSoDienCu;
    private javax.swing.JTextField txtSoDienMoi;
    private javax.swing.JTextField txtSoNuocCu;
    private javax.swing.JTextField txtSoNuocMoi;
    private javax.swing.JTextField txtThangNam;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
// Method can be used to open panel, no specific logic needed here
    }

    @Override
    public void setForm(DienNuoc entity) {
        if (entity != null) {
            txtDienNuoc.setText(String.valueOf(entity.getIdDienNuoc()));
            if (entity.getTenChiNhanh() != null) {
                cboChiNhanh.setSelectedItem(entity.getTenChiNhanh());
            } else {
                cboChiNhanh.setSelectedIndex(0);
            }
// Đặt mã phòng vào cboMaPhong
            if (entity.getSoPhong() != null) {
                cboMaPhong.setSelectedItem(entity.getSoPhong()); // Sử dụng soPhong để chọn item
            } else {
                cboMaPhong.setSelectedIndex(0);
            }
            txtSoDienCu.setText(String.valueOf(entity.getSoDienCu()));
            txtSoDienMoi.setText(String.valueOf(entity.getSoDienMoi()));
            txtSoNuocCu.setText(String.valueOf(entity.getSoNuocCu()));
            txtSoNuocMoi.setText(String.valueOf(entity.getSoNuocMoi()));
            if (entity.getThangNam() != null) {
                txtThangNam.setText(dateFormat.format(entity.getThangNam()));
            } else {
                txtThangNam.setText("");
            }
        } else {
            clear();
        }
    }

    public boolean validateForm() {
// This validation will be handled differently for create and update actions
// We'll keep a base validation here but specific checks will be done in create() and update()
        if (cboChiNhanh.getSelectedItem() == null || cboChiNhanh.getSelectedItem().equals("Tất cả")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một Chi nhánh hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cboChiNhanh.requestFocusInWindow();
            return false;
        }
        if (cboMaPhong.getSelectedItem() == null || cboMaPhong.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã phòng không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cboMaPhong.requestFocusInWindow();
            return false;
        }
        try {
            String selectedSoPhong = cboMaPhong.getSelectedItem().toString();
            Integer idPhong = phongMap.get(selectedSoPhong);
            if (idPhong == null) {
                JOptionPane.showMessageDialog(this, "Mã phòng không tồn tại trong chi nhánh đã chọn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                cboMaPhong.requestFocusInWindow();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi kiểm tra Mã phòng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return false;
        }
        return true;
    }

    @Override
    public DienNuoc getForm() {
// Phương thức này giờ sẽ chỉ lấy những dữ liệu cơ bản
        DienNuoc dienNuoc = new DienNuoc();
// Giữ lại ID_DienNuoc nếu đang ở chế độ sửa
        if (currentIndex >= 0 && currentIndex < currentList.size()) {
            dienNuoc.setIdDienNuoc(currentList.get(currentIndex).getIdDienNuoc());
        }
        String selectedSoPhong = cboMaPhong.getSelectedItem().toString();
        Integer idPhong = phongMap.get(selectedSoPhong); // Lấy ID phòng từ map
        if (idPhong == null) {
            JOptionPane.showMessageDialog(this, "Mã phòng không hợp lệ hoặc không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        dienNuoc.setIdPhong(idPhong);
        try {
            if (txtDienNuoc.getText() != null && !txtDienNuoc.getText().isEmpty()) {
                dienNuoc.setIdDienNuoc(Integer.parseInt(txtDienNuoc.getText()));
            }
            dienNuoc.setSoDienCu((int) Double.parseDouble(txtSoDienCu.getText()));
            dienNuoc.setSoDienMoi((int) Double.parseDouble(txtSoDienMoi.getText()));
            dienNuoc.setSoNuocCu((int) Double.parseDouble(txtSoNuocCu.getText()));
            dienNuoc.setSoNuocMoi((int) Double.parseDouble(txtSoNuocMoi.getText()));
            dienNuoc.setThangNam(dateFormat.parse(txtThangNam.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số điện hoặc số nước không hợp lệ. Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Tháng năm không hợp lệ. Vui lòng nhập theo định dạng YYYY-MM-DD.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ form: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return null;
        }
        return dienNuoc;
    }

    @Override
    public void create() {
        if (!validateForm()) {
            return;
        }
// Thêm validation mới cho nút thêm
        if (txtSoDienMoi.getText().isEmpty() || txtSoNuocMoi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện mới và Số nước mới không được để trống khi thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm mới bản ghi này?", "Xác nhận thêm mới", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DienNuoc newDienNuoc = new DienNuoc();
            String selectedSoPhong = cboMaPhong.getSelectedItem().toString();
            Integer idPhong = phongMap.get(selectedSoPhong);
            if (idPhong == null) {
                JOptionPane.showMessageDialog(this, "Mã phòng không hợp lệ hoặc không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            newDienNuoc.setIdPhong(idPhong);
            try {
                newDienNuoc.setSoDienCu((int) Double.parseDouble(txtSoDienMoi.getText()));
                newDienNuoc.setSoNuocCu((int) Double.parseDouble(txtSoNuocMoi.getText()));
                newDienNuoc.setSoDienMoi((int) 0.0);
                newDienNuoc.setSoNuocMoi((int) 0.0);
                newDienNuoc.setThangNam(dateFormat.parse(txtThangNam.getText()));
// Kiểm tra trùng lặp bản ghi
                DienNuoc existingDienNuoc = dienNuocDao.findByPhongThangNam(newDienNuoc.getIdPhong(),
                        newDienNuoc.getThangNam().getMonth() + 1,
                        newDienNuoc.getThangNam().getYear() + 1900);
                if (existingDienNuoc != null) {
                    JOptionPane.showMessageDialog(this, "Đã tồn tại bản ghi điện nước cho phòng này trong tháng và năm đã chọn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                dienNuocDao.create(newDienNuoc);
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                filterAndFillTable(); // Cập nhật lại bảng sau khi thêm
                clear();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số điện hoặc số nước không hợp lệ. Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (java.text.ParseException e) {
                JOptionPane.showMessageDialog(this, "Tháng năm không hợp lệ. Vui lòng nhập đúng định dạng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi thêm mới: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

  @Override
public void update() {
    if (currentIndex < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một bản ghi để cập nhật.");
        return;
    }

    String soDienMoiStr = txtSoDienMoi.getText().trim();
    String soNuocMoiStr = txtSoNuocMoi.getText().trim();
    String soDienCuStr = txtSoDienCu.getText().trim();
    String soNuocCuStr = txtSoNuocCu.getText().trim();

    // Thêm validation để kiểm tra các trường không được để trống
    if (soDienMoiStr.isEmpty() || soNuocMoiStr.isEmpty() || soDienCuStr.isEmpty() || soNuocCuStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Số điện cũ, Số nước cũ, Số điện mới và Số nước mới không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Thêm kiểm tra ID_Phong từ cboMaPhong để tránh lỗi FOREIGN KEY
    String selectedSoPhong = (String) cboMaPhong.getSelectedItem();
    Integer idPhong = phongMap.get(selectedSoPhong);
    if (idPhong == null) {
        JOptionPane.showMessageDialog(this, "Mã phòng không hợp lệ hoặc không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật bản ghi này?", "Xác nhận cập nhật", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            DienNuoc updatedDienNuoc = currentList.get(currentIndex);
            
            // Cập nhật ID_Phong mới nhất
            updatedDienNuoc.setIdPhong(idPhong);
            
            // Cập nhật giá trị mới từ các trường văn bản
            updatedDienNuoc.setSoDienMoi((int) Double.parseDouble(soDienMoiStr));
            updatedDienNuoc.setSoNuocMoi((int) Double.parseDouble(soNuocMoiStr));
            updatedDienNuoc.setSoDienCu((int) Double.parseDouble(soDienCuStr));
            updatedDienNuoc.setSoNuocCu((int) Double.parseDouble(soNuocCuStr));
            
            // Cập nhật ngày tháng
            if (txtThangNam.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tháng năm không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Date newThangNam = dateFormat.parse(txtThangNam.getText());
            updatedDienNuoc.setThangNam(newThangNam);

            // Kiểm tra trùng lặp tháng năm và phòng, nhưng bỏ qua bản ghi hiện tại đang sửa
            DienNuoc existingDienNuoc = dienNuocDao.findByPhongThangNam(updatedDienNuoc.getIdPhong(), updatedDienNuoc.getThangNam().getMonth() + 1, updatedDienNuoc.getThangNam().getYear() + 1900);
            if (existingDienNuoc != null && existingDienNuoc.getIdDienNuoc() != updatedDienNuoc.getIdDienNuoc()) {
                JOptionPane.showMessageDialog(this, "Đã tồn tại bản ghi điện nước cho phòng này trong tháng và năm đã chọn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            dienNuocDao.update(updatedDienNuoc);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            filterAndFillTable(); // Cập nhật lại bảng sau khi sửa
            clear();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số điện hoặc số nước không hợp lệ. Vui lòng chỉ nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Tháng năm không hợp lệ. Vui lòng nhập đúng định dạng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}

    @Override
    public void delete() {
        if (currentIndex < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một bản ghi để xóa.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa bản ghi này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int dienNuocIdToDelete = currentList.get(currentIndex).getIdDienNuoc();
                dienNuocDao.deleteById(dienNuocIdToDelete);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filterAndFillTable(); // Cập nhật lại bảng sau khi xóa
                clear();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi không xác định khi xóa: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    @Override
    public void clear() {
        cboChiNhanh.setSelectedIndex(0);
        cboMaPhong.setSelectedIndex(0); // Đặt lại cboMaPhong về mặc định
        txtSoDienCu.setText("");
        txtSoDienMoi.setText("");
        txtSoNuocCu.setText("");
        txtSoNuocMoi.setText("");
        txtDienNuoc.setText("");
        txtThangNam.setText(dateFormat.format(new Date())); // Đặt lại ngày hiện tại cho JTextField
        currentIndex = -1;
        setEditable(true);
        txtDienNuoc.setEditable(false); // Đảm bảo ID không sửa được
    }

    @Override
    public void edit() {
        int selectedRow = tblDienNuoc.getSelectedRow();
        if (selectedRow >= 0 && selectedRow < currentList.size()) {
            currentIndex = selectedRow;
            DienNuoc selectedDienNuoc = currentList.get(selectedRow);
            setForm(selectedDienNuoc);
            setEditable(true);
            txtDienNuoc.setEditable(false); // Mã điện nước thường không được sửa
        } else {
            clear();
        }
    }

    @Override
    public void setEditable(boolean editable) {
        cboMaPhong.setEnabled(editable); // Điều khiển cboMaPhong
        txtSoDienCu.setEditable(false);
        txtSoDienMoi.setEditable(editable);
        txtSoNuocCu.setEditable(false);
        txtSoNuocMoi.setEditable(editable);
        txtThangNam.setEditable(editable); // txtThangNam có thể chỉnh sửa
        cboChiNhanh.setEnabled(editable);
        btnThem.setEnabled(editable);
        btnSua.setEnabled(editable);
        btnXoa.setEnabled(editable);
        txtDienNuoc.setEditable(false); // Mã điện nước không cho sửa
    }
// Phương thức mới để vừa lọc vừa điền dữ liệu vào bảng

    public void filterAndFillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDienNuoc.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng hiện có
        String selectedChiNhanhName = (String) cboChiNhanh.getSelectedItem();
        try {
            List<DienNuoc> filteredList;
            if (selectedChiNhanhName == null || selectedChiNhanhName.equals("Tất cả")) {
                filteredList = dienNuocDao.findAll(); // Lấy tất cả nếu chọn "Tất cả"
            } else {
                Integer idChiNhanh = chiNhanhMap.get(selectedChiNhanhName);
                if (idChiNhanh != null) {
                    filteredList = dienNuocDao.findByChiNhanhId(idChiNhanh); // Lọc theo ID chi nhánh
                } else {
// Trường hợp không tìm thấy ID chi nhánh (có thể xảy ra nếu dữ liệu bị lỗi)
                    filteredList = new ArrayList<>(); // Trả về danh sách rỗng
                    JOptionPane.showMessageDialog(this, "Không tìm thấy ID cho chi nhánh đã chọn: " + selectedChiNhanhName, "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
            currentList = filteredList; // Cập nhật currentList
// --- BẮT ĐẦU ĐOẠN MÃ DEBUG ---
            System.out.println("--- DEBUG: Kiểm tra giá trị ID_DienNuoc từ currentList sau khi lọc ---");
            if (currentList != null) {
                for (DienNuoc dn : currentList) {
                    System.out.println(" ID_DienNuoc: " + dn.getIdDienNuoc()
                            + ", SoDienCu: " + dn.getSoDienCu()
                            + ", SoDienMoi: " + dn.getSoDienMoi()
                            + ", SoNuocCu: " + dn.getSoNuocCu()
                            + ", SoNuocMoi: " + dn.getSoNuocMoi()
                            + ", ThangNam: " + (dn.getThangNam() != null ? dateFormat.format(dn.getThangNam()) : "N/A")
                            + ", MaPhong: " + dn.getSoPhong()
                            + ", TenChiNhanh: " + dn.getTenChiNhanh());
                }
            } else {
                System.out.println(" currentList is null or empty.");
            }
            System.out.println("--- KẾT THÚC ĐOẠN MÃ DEBUG ---");
// Điền dữ liệu vào bảng từ currentList đã lọc
            for (DienNuoc dn : currentList) {
                Object[] row = {
                    dn.getTenChiNhanh(),
                    dn.getIdDienNuoc(),
                    dn.getSoPhong(),
                    dn.getSoDienCu(),
                    dn.getSoDienMoi(),
                    dn.getSoNuocCu(),
                    dn.getSoNuocMoi(),
                    dn.getThangNam() != null ? dateFormat.format(dn.getThangNam()) : "" // Định dạng ngày tháng
                };
                model.addRow(row);
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lọc và tải dữ liệu vào bảng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi không xác định khi lọc và tải dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
// fillToTable giờ chỉ gọi filterAndFillTable()

    @Override
    public void fillToTable() {
        filterAndFillTable();
    }

    private void loadChiNhanhToComboBox() {
        cboChiNhanh.removeAllItems();
        cboChiNhanh.addItem("Tất cả");
        chiNhanhMap.clear();
        try {
            List<ChiNhanh> chiNhanhs = chiNhanhDao.getAll();
            for (ChiNhanh cn : chiNhanhs) {
                cboChiNhanh.addItem(cn.getTenChiNhanh());
                chiNhanhMap.put(cn.getTenChiNhanh(), cn.getID_ChiNhanh());
            }
// Sau khi tải chi nhánh, tải phòng cho chi nhánh đầu tiên (hoặc "Tất cả")
            loadPhongToComboBox();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách chi nhánh: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
// Phương thức mới để tải mã phòng vào cboMaPhong dựa trên chi nhánh được chọn

    private void loadPhongToComboBox() {
        cboMaPhong.removeAllItems();
        phongMap.clear();
        String selectedChiNhanhName = (String) cboChiNhanh.getSelectedItem();
        System.out.println("DEBUG: Selected ChiNhanh: " + selectedChiNhanhName); // Debug
        if (selectedChiNhanhName == null || selectedChiNhanhName.equals("Tất cả")) {
// Nếu chọn "Tất cả" chi nhánh, tải tất cả các phòng
            try {
                List<Phong> phongs = phongDao.findAll(); // Sử dụng findAll từ CrudDao
                System.out.println("DEBUG: Loading all rooms. Found " + phongs.size() + " rooms."); // Debug
                for (Phong p : phongs) {
                    cboMaPhong.addItem(p.getSoPhong());
                    phongMap.put(p.getSoPhong(), p.getIdPhong());
                    System.out.println("DEBUG: Added room (All): " + p.getSoPhong() + " (ID: " + p.getIdPhong() + ", ChiNhanhID: " + p.getIdChiNhanh() + ")");
// Debug
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách phòng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            Integer idChiNhanh = chiNhanhMap.get(selectedChiNhanhName);
            System.out.println("DEBUG: Selected ChiNhanh ID: " + idChiNhanh); // Debug
            if (idChiNhanh != null) {
                try {
                    List<Phong> phongs = phongDao.findByChiNhanh(idChiNhanh); // Gọi phương thức findByChiNhanh
                    System.out.println("DEBUG: Loading rooms for ChiNhanh ID " + idChiNhanh + ". Found " + phongs.size() + " rooms."); // Debug
                    for (Phong p : phongs) {
                        cboMaPhong.addItem(p.getSoPhong());
                        phongMap.put(p.getSoPhong(), p.getIdPhong());
                        System.out.println("DEBUG: Added room (Filtered): " + p.getSoPhong() + " (ID: " + p.getIdPhong() + ", ChiNhanhID: " + p.getIdChiNhanh() + ")");
// Debug
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách phòng theo chi nhánh: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            } else {
                System.out.println("DEBUG: ChiNhanh ID is null for selected name: " + selectedChiNhanhName); // Debug
            }
        }
    }

    @Override
    public void checkAll() {
        tblDienNuoc.selectAll();
    }

    @Override
    public void uncheckAll() {
        tblDienNuoc.clearSelection();
    }

    @Override
    public void deleteCheckedItems() {
        int[] selectedRows = tblDienNuoc.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một bản ghi để xóa.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa " + selectedRows.length + " bản ghi đã chọn?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
// Xóa từ dưới lên để tránh lỗi index khi xóa
                for (int i = selectedRows.length - 1; i >= 0; i--) {
                    int modelRow = tblDienNuoc.convertRowIndexToModel(selectedRows[i]);
                    int dienNuocIdToDelete = currentList.get(modelRow).getIdDienNuoc();
                    dienNuocDao.deleteById(dienNuocIdToDelete);
                }
                JOptionPane.showMessageDialog(this, "Đã xóa các bản ghi đã chọn thành công!");
                filterAndFillTable(); // Cập nhật lại bảng sau khi xóa
                clear();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa các bản ghi đã chọn: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi không xác định khi xóa các bản ghi đã chọn: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    @Override
    public void moveFirst() {
        if (!currentList.isEmpty()) {
            currentIndex = 0;
            tblDienNuoc.setRowSelectionInterval(currentIndex, currentIndex);
            setForm(currentList.get(currentIndex));
        }
    }

    @Override
    public void movePrevious() {
        if (!currentList.isEmpty() && currentIndex > 0) {
            currentIndex--;
            tblDienNuoc.setRowSelectionInterval(currentIndex, currentIndex);
            setForm(currentList.get(currentIndex));
        }
    }

    @Override
    public void moveNext() {
        if (!currentList.isEmpty() && currentIndex < currentList.size() - 1) {
            currentIndex++;
            tblDienNuoc.setRowSelectionInterval(currentIndex, currentIndex);
            setForm(currentList.get(currentIndex));
        }
    }

    @Override
    public void moveLast() {
        if (!currentList.isEmpty()) {
            currentIndex = currentList.size() - 1;
            tblDienNuoc.setRowSelectionInterval(currentIndex, currentIndex);
            setForm(currentList.get(currentIndex));
        }
    }

    @Override
    public void moveTo(int rowIndex) {
        if (rowIndex >= 0 && rowIndex < currentList.size()) {
            currentIndex = rowIndex;
            tblDienNuoc.setRowSelectionInterval(currentIndex, currentIndex);
            setForm(currentList.get(currentIndex));
        }
    }

    private void Excel() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu file Excel");
        fileChooser.setSelectedFile(new File("DuLieuDienNuoc.xlsx"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().toLowerCase().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }
            try (Workbook workbook = new XSSFWorkbook(); FileOutputStream fileOut = new FileOutputStream(fileToSave)) {
                Sheet sheet = workbook.createSheet("Dữ liệu Điện Nước");
                DefaultTableModel model = (DefaultTableModel) tblDienNuoc.getModel();
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }
                for (int r = 0; r < model.getRowCount(); r++) {
                    Row dataRow = sheet.createRow(r + 1);
                    for (int c = 0; c < model.getColumnCount(); c++) {
                        Cell cell = dataRow.createCell(c);
                        Object value = model.getValueAt(r, c);
                        if (value != null) {
                            if (value instanceof String) {
                                cell.setCellValue((String) value);
                            } else if (value instanceof Number) {
                                cell.setCellValue(((Number) value).doubleValue());
                            } else {
                                cell.setCellValue(value.toString());
                            }
                        } else {
                            cell.setCellValue("");
                        }
                    }
                }
                workbook.write(fileOut);
                JOptionPane.showMessageDialog(this, "Xuất file Excel thành công!\nĐường dẫn: " + fileToSave.getAbsolutePath(), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất file Excel: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }
}
