/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.nhatro.ui;

import poly.nhatro.controller.GopYController;
import javax.swing.table.DefaultTableModel; // Vẫn cần
import javax.swing.JOptionPane;

/**
 *
 * @author Gia Bao
 */
public class GopYJdilog extends javax.swing.JDialog {
    private GopYController gopYController; // Thay đổi kiểu dữ liệu thành Controller cụ thể
    

    /**
     * Creates new form GopYJdilog
     */
    public GopYJdilog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        // Khởi tạo Controller và truyền chính dialog này vào
        // Đây là dòng quan trọng nhất gây lỗi trước đó nếu hàm tạo của Controller không nhận tham số
        gopYController = new GopYController(this); // Dòng này là đúng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGopY = new javax.swing.JPanel();
        lblNameGopY = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGopY = new javax.swing.JTable();
        lblIDGopY = new javax.swing.JLabel();
        txtIDGopY = new javax.swing.JTextField();
        lblNoiDung = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        lblIDNguoiDung = new javax.swing.JLabel();
        txtIDNguoiDung = new javax.swing.JTextField();
        lblIDChiNhanh = new javax.swing.JLabel();
        txtIDChiNhanh = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlGopY.setBackground(new java.awt.Color(255, 255, 255));

        lblNameGopY.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNameGopY.setText("GÓP Ý");

        tblGopY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã góp ý", "Nội dung", "Mã người dùng", "Mã chi nhánh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGopY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGopYMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGopY);

        lblIDGopY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDGopY.setText("Mã góp ý");

        lblNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoiDung.setText("Nội dung");

        lblIDNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDNguoiDung.setText("Mã người dùng");

        lblIDChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDChiNhanh.setText("Mã chi nhánh");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Làm mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGopYLayout = new javax.swing.GroupLayout(pnlGopY);
        pnlGopY.setLayout(pnlGopYLayout);
        pnlGopYLayout.setHorizontalGroup(
            pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGopYLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(26, 26, 26)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnMoi)
                .addGap(22, 22, 22))
            .addGroup(pnlGopYLayout.createSequentialGroup()
                .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGopYLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(lblNameGopY, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGopYLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNoiDung)
                            .addComponent(lblIDGopY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDGopY, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDNguoiDung)
                            .addComponent(lblIDChiNhanh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 294, Short.MAX_VALUE))
        );
        pnlGopYLayout.setVerticalGroup(
            pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGopYLayout.createSequentialGroup()
                .addComponent(lblNameGopY)
                .addGap(32, 32, 32)
                .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDGopY)
                    .addComponent(txtIDGopY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDNguoiDung)
                    .addComponent(txtIDNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNoiDung)
                        .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIDChiNhanh))
                    .addComponent(txtIDChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlGopYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGopY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGopY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
          gopYController.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        gopYController.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblGopYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGopYMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 1) { // Chỉ xử lý click chuột trái 1 lần
            gopYController.edit(); // Gọi phương thức edit trong controller
        }
    }//GEN-LAST:event_tblGopYMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        gopYController.clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GopYJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GopYJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GopYJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GopYJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GopYJdilog dialog = new GopYJdilog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMoi;
    public javax.swing.JButton btnSua;
    public javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDChiNhanh;
    private javax.swing.JLabel lblIDGopY;
    private javax.swing.JLabel lblIDNguoiDung;
    private javax.swing.JLabel lblNameGopY;
    private javax.swing.JLabel lblNoiDung;
    private javax.swing.JPanel pnlGopY;
    public javax.swing.JTable tblGopY;
    public javax.swing.JTextField txtIDChiNhanh;
    public javax.swing.JTextField txtIDGopY;
    public javax.swing.JTextField txtIDNguoiDung;
    public javax.swing.JTextField txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
